apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: node-app
spec:
  replicas: 1
  selector:
  ## services pick correspondind pods with the labels
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app-container
        image: test123456787654/test-repo:init1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        ## resource limitations for the containers
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "250m"
            memory: "250Mi"
        securityContext:
          ## this enables the container to run as  non-root user, but the creation of pod needs root acces, hence disabled it
          #          runAsNonRoot: true
          ## filesystem is made readonly
          readOnlyRootFilesystem: true
          ## disallow privilege escalation.
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        ## livenessProbe and readinessProbe    
        livenessProbe:
          httpGet:
            path: /info
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
